# NOTE: update this with your service name
service: bayad-tech-exam-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1  
  environment:
    MYSQL_ENDPOINT: ${env:MYSQL_ENDPOINT}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE}
    MYSQL_USERNAME: ${env:MYSQL_USERNAME}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}

functions:  
  postUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
  
  getUser:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get

  getUsers:
    handler: handler.users
    events:
      - http:
          path: users
          method: get

  putUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
